import { Action } from "./action";
import { Base } from "../shared/base";
import { Unit } from "./unit";

export class Instruction extends Base {
  Action?:Action; // Bake, Whip, etc...
  Target:string = ""; // cream, cake, etc...

  Temperature?:Unit; // 200'c, 50'f ...
  
  Duration?:Unit; // 15 seconds, 1 hour ....
}